language: csharp
solution: Hopefully.sln
install:
    - nuget restore Hopefully.sln
    - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
    - xbuild /p:Configuration=Release Hopefully.sln
    - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Hopefully.Tests/bin/Release/Hopefully.Tests.dll
